runtime: nodejs
env: flex
service: cinematheque-front
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/cinematheque-front/\1
    upload: dist/cinematheque-front/(.*\..+)$ # catch all handler to index.html
  - url: /.*
    static_files: dist/cinematheque-front/main.js
    upload: dist/cinematheque-front/main.js
