runtime: nodejs16
service: cinematheque-front
handlers:
  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/cinematheque-front/\1
    upload: dist/cinematheque-front/(.*)(|\.map)
  - url: /(.*)
    static_files: dist/cinematheque-front/index.js
    upload: dist/cinematheque-front/index.js
