runtime: nodejs16
service: cinematheque-front
handlers:
  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/cinematheque-front/\1
    upload: dist/cinematheque-front/(.*)(|\.map)
  - url: /(.*)
    static_files: dist/cinematheque-front/index.html
    upload: dist/cinematheque-front/index.html
skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
